//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EventData
    {
        [DisplayName("Event ID")]
        public int eventID { get; set; }
        [DisplayName("Event Title")]
        public string eventTitle { get; set; }

        [DisplayName("Start Date")] 
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime eventStartDate
        {   get; set;     }

            [DisplayName("Duration(In Minutes)")]
        public Nullable<int> eventDurationInMin { get; set; }
    }
}
