//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginData
    {
        [DisplayName("Username")]
        [Required(ErrorMessage = "Please enter your name")]
        public string userName { get; set; }

        [Required(ErrorMessage = "Please enter your password")]
        [DisplayName("Password")]
        public string password { get; set; }
    }
}
